### PR TITLE
chakrashim: add warning for ignored engine flags

### LINKED ISSUE #486: `react-scripts-ts` module tries to use unsupported option `--max-old-space-size`
<!--
Thank you for reporting an issue.

This issue tracker is for bugs and issues found within Node.js core.
If you require more general support please file an issue on our help
repo. https://github.com/nodejs/help


Please fill in as much of the template below as you're able.

Version: output of `node -v`
Platform: output of `uname -a` (UNIX), or version and 32 or 64-bit (Windows)
Subsystem: if known, please specify affected core module name

If possible, please provide code that demonstrates the problem, keeping it as
simple and free of external dependencies as you are able.
-->

* **Version**: all
* **Platform**: all
* **Subsystem**: chakrashim

<!-- Enter your issue details below this comment. -->
While trying to use `react-script-ts` to build a TypeScript React app I ran into an issue where compilation fails due to an unsupported option being passed to the node executable:  `bad option: --max-old-space-size=2048`.

The repro is pretty simple:

```console
[KFARNUNG1] E:\GitHub                                                                                                                                                                                                                           
> npm install -g create-react-app                                                                                                                                                                                                               
C:\Users\kfarnung\AppData\Local\nvs\chakracore\8.9.4\x64\create-react-app -> C:\Users\kfarnung\AppData\Local\nvs\chakracore\8.9.4\x64\node_modules\create-react-app\index.js                                                                    
+ create-react-app@1.5.2                                                                                                                                                                                                                        
updated 1 package in 5.851s                                                                                                                                                                                                                     
[KFARNUNG1] E:\GitHub                                                                                                                                                                                                                           
> create-react-app --scripts-version=react-scripts-ts my-app                                                                                                                                                                                    
                                                                                                                                                                                                                                                
Creating a new React app in E:\GitHub\my-app.                                                                                                                                                                                                   
                                                                                                                                                                                                                                                
Installing packages. This might take a couple of minutes.                                                                                                                                                                                       
Installing react, react-dom, and react-scripts-ts...                                                                                                                                                                                            
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                
> uglifyjs-webpack-plugin@0.4.6 postinstall E:\GitHub\my-app\node_modules\uglifyjs-webpack-plugin                                                                                                                                               
> node lib/post_install.js                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                
+ react@16.2.0                                                                                                                                                                                                                                  
+ react-scripts-ts@2.13.0                                                                                                                                                                                                                       
+ react-dom@16.2.0                                                                                                                                                                                                                              
added 1219 packages in 97.966s                                                                                                                                                                                                                  
Installing @types/node, @types/react, @types/react-dom, @types/jest, typescript as dev dependencies npm...                                                                                                                                      
                                                                                                                                                                                                                                                
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):                                                                                                                                                         
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})                                                                               
                                                                                                                                                                                                                                                
+ @types/react-dom@15.5.7                                                                                                                                                                                                                       
+ @types/react@16.0.40                                                                                                                                                                                                                          
+ @types/jest@22.2.0                                                                                                                                                                                                                            
+ @types/node@9.4.6                                                                                                                                                                                                                             
+ typescript@2.7.2                                                                                                                                                                                                                              
added 6 packages in 25.202s                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                
Success! Created my-app at E:\GitHub\my-app                                                                                                                                                                                                     
Inside that directory, you can run several commands:                                                                                                                                                                                            
                                                                                                                                                                                                                                                
  npm start                                                                                                                                                                                                                                     
    Starts the development server.                                                                                                                                                                                                              
                                                                                                                                                                                                                                                
  npm run build                                                                                                                                                                                                                                 
    Bundles the app into static files for production.                                                                                                                                                                                           
                                                                                                                                                                                                                                                
  npm test                                                                                                                                                                                                                                      
    Starts the test runner.                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                
  npm run eject                                                                                                                                                                                                                                 
    Removes this tool and copies build dependencies, configuration files                                                                                                                                                                        
    and scripts into the app directory. If you do this, you can’t go back!                                                                                                                                                                      
                                                                                                                                                                                                                                                
We suggest that you begin by typing:                                                                                                                                                                                                            
                                                                                                                                                                                                                                                
  cd my-app                                                                                                                                                                                                                                     
  npm start                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                
Happy hacking!                                                                                                                                                                                                                                  
[KFARNUNG1] E:\GitHub                                                                                                                                                                                                                           
> cd .\my-app\                                                                                                                                                                                                                                  
[KFARNUNG1] E:\GitHub\my-app                                                                                                                                                                                                                    
> npm run build                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                
> my-app@0.1.0 build E:\GitHub\my-app                                                                                                                                                                                                           
> react-scripts-ts build                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                
Failed to load tsconfig.json: Missing baseUrl in compilerOptions                                                                                                                                                                                
Creating an optimized production build...                                                                                                                                                                                                       
Found no baseUrl in tsconfig.json, not applying tsconfig-paths-webpack-plugin                                                                                                                                                                   
Found no baseUrl in tsconfig.json, not applying tsconfig-paths-webpack-plugin                                                                                                                                                                   
C:\Users\kfarnung\AppData\Local\nvs\chakracore\8.9.4\x64\node.exe: bad option: --max-old-space-size=2048                                                                                                                                        
Starting type checking and linting service...                                                                                                                                                                                                   
Using 1 worker with 2048MB memory limit                                                                                                                                                                                                         
Cannot start checker service: Error: write EPIPE                                                                                                                                                                                                
ts-loader: Using typescript@2.7.2 and E:\GitHub\my-app\tsconfig.json
```

### PR DESCRIPTION
**Pull request by kfarnung**
* Added a warning for any ignored engine-specific flags.
* Added `--max-old-space-size=` to the list of ignored flags.

Fixes #486

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md#commit-message-guidelines)

### CODE REVIEW

File: deps/chakrashim/src/v8v8.cc [hunk 1]
```diff
@@ -142,18 +139,22 @@ void V8::SetFlagsFromCommandLine(int *argc, char **argv, bool remove_flags) {
...
-                || startsWith(arg, "--stack-size=")
-                || startsWith(arg, "--nolazy"))) {
-      argv[i] = nullptr;
+    } else if (startsWith(arg, "--debug") ||
+               startsWith(arg, "--harmony") ||
+               startsWith(arg, "--stack-size=") ||
+               startsWith(arg, "--nolazy") ||
+               startsWith(arg, "--max-old-space-size=")) {
+      // Ignore some flags to reduce unit test noise
+      fprintf(stderr, "Warning: Ignored engine flag: %s\n", arg);
```
Comment (kfarnung) [inline deps/chakrashim/src/v8v8.cc]: This doesn't seem to bother any of the unit tests, but I'll have to check that VS Code doesn't get upset about it (I doubt it).  I'd say we either have a warning for all of these flags or none of them.

**Comment by kfarnung** [comment]
On Windows at least the `react-scripts-ts` build made a mess of the warning, but I'm not really worried about it right now:

```console
> react-scripts-ts build

Failed to load tsconfig.json: Missing baseUrl in compilerOptions
Creating an optimized production build...
Found no baseUrl in tsconfig.json, not applying tsconfig-paths-webpack-plugin
Found no baseUrl in tsconfig.json, not applying tsconfig-paths-webpack-plugin
Warning: Unsupported engine flag:Starting type checking and linting service...
 --Using m1 workera with x2048MB- memory limit
old-space-size=2048
ts-loader: Using typescript@2.7.2 and D:\Samples\my-app\tsconfig.json
Compiled successfully.

File sizes after gzip:

  35.45 KB  build\static\js\main.ceb68587.js
  300 B     build\static\css\main.29266132.css

The project was built assuming it is hosted at the server root.
To override this, specify the homepage in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build
```

The good news is that `npm start` and `npm run build` both worked without issues with this change.

**Comment by kfarnung** [comment]
CI: https://ci.nodejs.org/job/chakracore-test-pull-request/226/

**Review by sethbrenith — APPROVED** [review]
:shipit:

**Comment by kfarnung** [comment]
One more CI: ~~https://ci.nodejs.org/job/chakracore-test-pull-request/230/~~
https://ci.nodejs.org/job/chakracore-test-pull-request/231/

**Comment by kfarnung** [comment]
@mrkmarron @digitalinfinity I added an eslint ignore to trace_mgr.js due to a new rule about using `Error` objects in the `lib/` directory.  I believe this is the right fix here since we never let this error object leave the scope.
