### PR TITLE
Fix v8 build break

### LINKED ISSUE #354: Node-chakracore V8 build break on Ubuntu 16.04
To reproduce:
1. git clone the latest node-chakracore repo:
git clone https://github.com/nodejs/node-chakracore.git

2. cd to node-chakracore folder:
cd ~/GitHub/node-chakracore

3. make configuration  to v8 engine:
./configure --engine=v8

4. build:
make

We encountered following build break errors:

g++ '-DNODE_ENGINE="v8"' '-DNODE_ENGINE_V8' '-DNODE_ARCH="x64"' '-DNODE_PLATFORM="linux"' '-DNODE_WANT_INTERNALS=1' '-DV8_DEPRECATION_WARNINGS=1' '-DNODE_USE_V8_PLATFORM=1' '-DNODE_HAVE_I18N_SUPPORT=1' '-DNODE_HAVE_SMALL_ICU=1' '-DHAVE_INSPECTOR=1' '-DHAVE_OPENSSL=1' '-D__POSIX__' '-DUCONFIG_NO_SERVICE=1' '-DUCONFIG_NO_REGULAR_EXPRESSIONS=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=0' '-DUCONFIG_NO_BREAK_ITERATION=0' '-DHTTP_PARSER_STRICT=0' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D_POSIX_C_SOURCE=200112' -I../src -I../tools/msvs/genfiles -I../deps/uv/src/ares -I/home/li2/GitHub/node-chakracore/out/Release/obj/gen -I/home/li2/GitHub/node-chakracore/out/Release/obj/gen/include -I../deps/v8/include -I../deps/icu-small/source/i18n -I../deps/icu-small/source/common -I../deps/openssl/openssl/include -I../deps/zlib -I../deps/http_parser -I../deps/cares/include -I../deps/uv/include  -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF /home/li2/GitHub/node-chakracore/out/Release/.deps//home/li2/GitHub/node-chakracore/out/Release/obj.target/node/src/async-wrap.o.d.raw   -c -o /home/li2/GitHub/node-chakracore/out/Release/obj.target/node/src/async-wrap.o ../src/async-wrap.cc
In file included from ../src/base-object-inl.h:29:0,
                 from ../src/async-wrap-inl.h:29,
                 from ../src/async-wrap.cc:23:
../src/env-inl.h: In constructor ‘node::Environment::AsyncHooks::AsyncHooks(v8::Isolate*)’:
../src/env-inl.h:87:7: error: class ‘node::Environment::AsyncHooks’ does not have any field named ‘uid_fields_ttdRef’
       uid_fields_ttdRef(nullptr) {
       ^
node.target.mk:197: recipe for target '/home/li2/GitHub/node-chakracore/out/Release/obj.target/node/src/async-wrap.o' failed
make[1]: *** [/home/li2/GitHub/node-chakracore/out/Release/obj.target/node/src/async-wrap.o] Error 1
rm 54c66d5aebf0b1cc95f8c1b6d449cc5ec5463317.intermediate
Makefile:76: recipe for target 'node' failed
make: *** [node] Error 2

Note: The output for "uname -a":
Linux li2-ubuntu 4.8.0-39-generic #42~16.04.1-Ubuntu SMP Mon Feb 20 15:06:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### PR DESCRIPTION
**Pull request by kunalspathak**
Addressed v8 build break. Also ran through unit test and fixed 2 test cases. There are still 2 unit test failures in inspector that are failing for node-v8. @kfarnung  might have idea.

* inspector/test-bindings
* inspector/test-off-with-session-then-on

Fixes: #354 

##### Checklist

- [x] `make -j4 test` (UNIX), or `vcbuild test` (Windows) passes
- [x] commit message follows [commit guidelines](https://github.com/nodejs/node/blob/master/CONTRIBUTING.md#commit-message-guidelines)

##### Affected core subsystem(s)

src,test

### CODE REVIEW

File: test/parallel/test-vm-new-script-new-context.js [hunk 1]
```diff
@@ -42,14 +42,16 @@ const Script = require('vm').Script;
...
 {
-  assert.throws(
-    function() {
-      script.runInNewContext();
-    },
-    common.engineSpecificMessage({
-      v8: /^ReferenceError: foo is not defined$/,
-      chakracore: /ReferenceError: Use before declaration/
-    }));
+  const script = new Script('foo.bar = 5;');
```
Comment (kfarnung) [inline test/parallel/test-vm-new-script-new-context.js:45]: I'm assuming this was just a bad merge?

**Review by kfarnung — APPROVED** [review]

**Review by MSLaguana — APPROVED** [review]

File: test/parallel/test-vm-new-script-new-context.js (hunk 1 above)
Comment (kunalspathak) [reply test/parallel/test-vm-new-script-new-context.js:45]: yep.
